### ISSUE TITLE
Implement Spotify Auth Flow

### ISSUE THREAD

**Issue by peddybeats** [PedramPejman/jukebox#1]
- Add new HTTP.GET endpoint to FE to handle user requests (at '/home', we'll change it to root later)
- Add the logic to handle the implicit grant auth flow
- Add a callback HTTP.GET endpoint to FE's server at '/auth-callback'
- Verify correctness by visiting /home on your browser
- Please do this on a separate branch and submit a pull request when you're done :)

Use the following client id: c99f31ef396d40ffb498f24d1803b17f

**Comment by PedramPejman** [comment]
Just a note: make sure you don't include our app secret in any file you check into git. The correct way of dealing with this is using secrets in kubernetes files but if you don't wanna deal with all that just have a local js file (called secret.js, which you won't check into git) that exports the secret and include it in your main js file.

**Comment by peddybeats** [comment]
e27fcc9dee7e66ffc21b033007a4240c3f60ae8a
