### ISSUE TITLE
[148.2] Do preliminary scoping/design of Yoda's JukeboxCreatedSubscriber

### ISSUE THREAD

**Issue by peddybeats** [PedramPejman/jukebox#150]
- @PeymanPejman this is more of an educational issue - we're implementing a fairly sophisticated I/O pipeline so you should put time in upfront understanding how Cloud PubSub works and a the java implementation of couple data structures that offer advanced I/O functionality.
- First understand the [value proposition of a pubsub system](https://cloud.google.com/pubsub/)
- Just a note, we'll be using pull sync topology (as opposed to push) - which means you subscriber has to keep running and poll the pubsub server for updates (need to figure out what's a good frequency for this poll - thinking 60 seconds for now)
- Read [client library usage](https://cloud.google.com/pubsub/docs/quickstart-client-libraries#pubsub-client-libraries-java) (in Java)
- Make sure you understand every single line in their SubscriberExample (this includes the behavior of BlockingQueues)
- Then think about how you will structure your implementation of the subscriber
- I have a high-level design for how you could do this, but you should take a stab at it and then we can compare designs and finalize :) 
  - Just know, I'll inject GCP_PROJECT_ID, JUKEBOX_CREATED_YODA_SUBSCRIPTION_ID  into the environment in which your process will run (meaning you don't have to worry about where they come from!)

**Comment by PeymanPejman** [comment]
Are we using the sync pull as opposed to the async pull to be able to poll only every x minutes/hours? 
How are the env variables supplied for multiple topics? 

Structure of YodaSubscriber: We will have two classes. One is YodaSubscriberClient the other is MesssageReciever. The Yoda/subscriberClient creates a subscription  and attaches a MessageReciever to it. The MessageReciever handles the logic of receiving/processing the messages.

**Comment by peddybeats** [comment]
I agree that sync gives us the ability to pull with a pre-determined frequency but... if we use it, we'll have to manage the threading ourselves.. At the end of the day it's up to you but I can foresee the sync implementation requiring some low-level design considerations..

I'm not sure what you mean by "env variables supplied for multiple topics?" 
For every topic named X you can expect to see X_YODA_SUBSCRIPTION_ID in your environment. I don't see our user journey getting so long/complicated that we have more than a few topics but if we hit that scaling barrier, we can design a better mechanism for cross-service pubsub topic discovery.

Re design: seems reasonable to me. Only naming comments:

- s/YodaSubscriberClient/{YodaPubSubClient | YodaSubscriber}
- MessageReceiver is an interface.. you should name your receiver class JukeboxCreatedMessageReceiver that implements MessageReceiver

Feel free to close this issue and start work on #153 :)

**Comment by peddybeats** [comment]
I take back my first suggestion - YodaSubscriberClient is a better name

**Comment by PeymanPejman** [comment]
You had mentioned we should use pull sync topology otherwise I thought about the same thing. Async will be less cumbersome.

**Comment by peddybeats** [comment]
ahh apologies - I meant pull synchronization topology, not synchronous pull synchronization topology..
