### ISSUE TITLE
Implement layout for home page 

### ISSUE THREAD

**Issue by peddybeats** [PedramPejman/jukebox#17]
- Needs to be mobile responsive (perhaps use flexbox)
- Desktop: 2 horizontal containers, equal width 
- Mobile: 2 vertical containers, equal height
- Skin should be black low-lights with green/blue high-lights with Spotify font
- Feel should be slick (not too professional or too playful)

**Comment by PedramPejman** [comment]
We cannot use iframe widgets because of our speed requirement.

**Comment by peddybeats** [comment]
#33
